variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1
  GIT_FETCH_EXTRA_FLAGS: --prune

stages:
  - build
  - release

release_project:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Running release from v2.1.4"
  release:
    name: "Sigtools v2.1.4"
    description: 'Sigtools v2.1.4'
    tag_name: 'v2.1.4'
    ref: 'v2.1.4'

build:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: build
  image: electronuserland/builder:wine
  script:
    - echo "Running build from v2.1.4"
    - yarn
    - yarn dist:win
  artifacts:
    expire_in: 30 days
    paths:
      - ./release/ 