stages:
    - realese

 release-project:
   stage: release
   image: registry.gitlab.com/gitlab-org/realese-cli:latest
   rules:
     - if: $CI_COMMIT_TAG                                            # Run this job when a tag is created manually
   script:
     - echo "running release from $CI_COMMIT_TAG"
   release:
     name: "Release $CI_COMMIT_TAG"
     description: 'Release $CI_COMMIT_TAG'
     tag_name: '$CI_COMMIT_TAG'
     ref: '$CI_COMMIT_TAG'