variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1
  GIT_FETCH_EXTRA_FLAGS: --prune

stages:
  - rrtest

RRTest:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: rrtest
  when: manual
  image: electronuserland/builder:wine
  script:
    - echo Running RR Test
    - cd  /builds/printegrador/2022/pe38-sigarratools
    - yarn
    - yarn dist:win
    - ls -la dist
  artifacts:
    paths:
      - dist/*.zip

