stages:
  - build
  - upload
  - release

variables:
  GIT_STRATEGY: clone
  SIGTOOLS_BINARY: "Sigtools ${CI_COMMIT_TAG}"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/release/${CI_COMMIT_TAG}/"

build:
  image: electronuserland/builder:wine
  stage: build
  script:
    - yarn
    - yarn dist:win
  artifacts:
    expire_in: 30 days
    paths:
      - ./release/
  only:
    - master

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/${SIGTOOLS_BINARY} ${PACKAGE_REGISTRY_URL}

release_project:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    |
      release-cli create --name "Sigtools $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${SIGTOOLS_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}${SIGTOOLS_BINARY}\"}"
  release:
    name: "Sigtools $CI_COMMIT_TAG"
    description: 'Sigtools $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'