variables:
  GIT_STRATEGY: clone

stages:
  - build
  - release

release_project:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Running release from $CI_COMMIT_TAG"
  release:
    name: "Sigtools $CI_COMMIT_TAG"
    description: 'Sigtools $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'

build:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: build
  image: electronuserland/builder:wine
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Running build from $CI_COMMIT_TAG"
    - npm
    - npm dist:win
  artifacts:
    expire_in: 30 days
    paths:
      - ./release/ 