variables:
  GIT_STRATEGY: none
  GIT_DEPTH: 1
  GIT_FETCH_EXTRA_FLAGS: --prune

stages:
  - rrtest

RRTest:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: rrtest
  when: manual
  image: electronuserland/builder:wine
  script:
    - echo Running RR Test script
    - mkdir -p /builds/printegrador/2022/pe38-sigarratools
    - cd  /builds/printegrador/2022/pe38-sigarratools
    - git config --global http.postBuffer 524288000
    - git -c 'http.userAgent=gitlab-runner 15.0.0 linux/amd64' clone -n rr-auto-release https://gitlab-ci-token:${CI_JOB_TOKEN}@git.fe.up.pt/printegrador/2022/pe38-sigarratools.git --depth 1
    - ls -la


