variables:
  GIT_STRATEGY: clone

stages:
  - release
  - build

release_project:
   stage: release
   image: registry.gitlab.com/gitlab-org/release-cli:latest
   rules:
     - if: $CI_COMMIT_TAG
   script:
     - echo "Running release from $CI_COMMIT_TAG"
   release:
     name: "Sigtools $CI_COMMIT_TAG"
     description: 'Sigtools $CI_COMMIT_TAG'
     tag_name: '$CI_COMMIT_TAG'
     ref: '$CI_COMMIT_TAG'

build:
  variables:
    CI_DEBUG_TRACE: "true"
  image: electronuserland/builder:wine
  stage: build
  script:
    - echo "Running build from $CI_COMMIT_TAG"
    - yarn
    - yarn dist:win
  artifacts:
    expire_in: 30 days
    paths:
      - ./release/
  only:
    - master     