stages:
  - release

release_project:
   stage: release
   image: registry.gitlab.com/gitlab-org/release-cli:v0.4.0
   rules:
     - if: $CI_COMMIT_TAG
   script:
     - echo "Running release from $CI_COMMIT_TAG"
   release:
     name: "Release $CI_COMMIT_TAG"
     description: 'Release $CI_COMMIT_TAG'
     tag_name: '$CI_COMMIT_TAG'
     ref: '$CI_COMMIT_TAG'