variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 1
  GIT_FETCH_EXTRA_FLAGS: --prune

stages:
  - rrtest

RRTest:
  variables:
    #CI_DEBUG_TRACE: "true"
    ELECTRON_CACHE: "$CI_PROJECT_DIR/.cache/electron"
    ELECTRON_BUILDER_CACHE: "$CI_PROJECT_DIR/.cache/electron-builder"
    RELEASE_PACKAGE: "Sigtools-2.1.2-win.7z"
  stage: rrtest
  when: manual
  image: electronuserland/builder:wine
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/
      - node_modules/
  script:
    - echo Running RR Test
    - cd  $CI_PROJECT_DIR
    - yarn
    - yarn dist:win
    - ls -la dist
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/${RELEASE_PACKAGE} "${PACKAGE_REGISTRY_URL}/${RELEASE_PACKAGE}"
  artifacts:
    paths:
      - dist/*.7z

