variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1
  GIT_FETCH_EXTRA_FLAGS: --prune

stages:
  - rrtest

RRTest:
  variables:
    CI_DEBUG_TRACE: "true"
    ELECTRON_CACHE: "$CI_PROJECT_DIR/.cache/electron"
    ELECTRON_BUILDER_CACHE: "$CI_PROJECT_DIR/.cache/electron-builder"
  stage: rrtest
  when: manual
  image: electronuserland/builder:wine
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache/
      - node_modules/
  script:
    - echo Running RR Test
    - cd  $CI_PROJECT_DIR
    - yarn
    - yarn dist:win
    - ls -la dist
  #artifacts:
   # paths:
    #  - dist/*.zip

