variables:
  GIT_STRATEGY: none
  GIT_DEPTH: 1
  GIT_FETCH_EXTRA_FLAGS: --prune

stages:
  - rrtest

RRTest:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: rrtest
  when: manual
  image: electronuserland/builder:wine
  script:
    - echo Running RR Test script


